version: "3.7"
services:

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-livewire-jetstream-tailwind-network
    depends_on:
      - app

  app:
    build:
      args:
        user: Ridoy
        uid: 1000
      context: ./.docker/app
      dockerfile: Dockerfile
    image: laravel-livewire-jetstream-tailwind
    container_name: laravel-livewire-jetstream-tailwind
    restart: unless-stopped
    ports: 
        - 6001:6001
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    networks:
      - laravel-livewire-jetstream-tailwind-network
    depends_on:
      - database

  database:
    image: mariadb:10.5.8
    container_name: db
    restart: unless-stopped
    ports:
      - 3304:3304
    volumes:
      - laravel-livewire-jetstream-tailwind-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - laravel-livewire-jetstream-tailwind-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-livewire-jetstream-tailwind-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - 8088:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 1000M
    networks:
      - laravel-livewire-jetstream-tailwind-network
      
networks:
  laravel-livewire-jetstream-tailwind-network:
    driver: bridge

volumes:
  laravel-livewire-jetstream-tailwind-volume:
    driver: local
